using DocVault.Domain.Entities;
using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;

namespace DocVault.Infrastructure.Services;

internal static class PdfMergeHelper
{
    private static readonly XColor Purple = XColor.FromArgb(124, 58, 237);
    private static readonly XColor Gray   = XColor.FromArgb(107, 114, 128);
    private static readonly XColor Light  = XColor.FromArgb(245, 243, 255);

    public static void AddCoverPage(PdfDocument output, List<Document> docs)
    {
        var page = output.AddPage();
        page.Width  = XUnit.FromPoint(595);
        page.Height = XUnit.FromPoint(842);

        using var gfx = XGraphics.FromPdfPage(page);

        // Header band
        gfx.DrawRectangle(new XSolidBrush(Purple), 0, 0, page.Width, 120);

        var titleFont  = new XFont("Arial", 26, XFontStyle.Bold);
        var subtitleFont = new XFont("Arial", 11, XFontStyle.Regular);
        var bodyFont   = new XFont("Arial", 10, XFontStyle.Regular);
        var boldFont   = new XFont("Arial", 10, XFontStyle.Bold);
        var smallFont  = new XFont("Arial", 8,  XFontStyle.Regular);

        gfx.DrawString("DocVault", titleFont, XBrushes.White, new XRect(40, 28, page.Width - 80, 40), XStringFormats.TopLeft);
        gfx.DrawString("Merged Document Report", subtitleFont, XBrushes.White, new XRect(40, 68, page.Width - 80, 24), XStringFormats.TopLeft);

        // Generated date
        gfx.DrawString($"Generated: {DateTime.UtcNow:dd MMM yyyy HH:mm} UTC  ·  Total: {docs.Count} document{(docs.Count == 1 ? "" : "s")}",
            smallFont, new XSolidBrush(Gray), new XRect(40, 140, page.Width - 80, 20), XStringFormats.TopLeft);

        // Table header
        double y = 174;
        gfx.DrawRectangle(new XSolidBrush(Light), 32, y, page.Width - 64, 22);
        DrawRow(gfx, boldFont, XBrushes.Black, y + 5, "#", "Title", "Uploader", "Department", "FY", "Uploaded");

        y += 22;
        for (int i = 0; i < docs.Count && y < page.Height - 60; i++)
        {
            var d = docs[i];
            if (i % 2 == 1) gfx.DrawRectangle(new XSolidBrush(XColor.FromArgb(250, 250, 250)), 32, y, page.Width - 64, 20);
            DrawRow(gfx, bodyFont, new XSolidBrush(XColor.FromArgb(31, 41, 55)), y + 4,
                (i + 1).ToString(),
                Truncate(d.Title, 36),
                Truncate(d.User?.FullName ?? "", 20),
                Truncate(d.Department?.Name ?? "", 18),
                d.FinancialYear?.Label ?? "",
                d.UploadedAt.ToLocalTime().ToString("dd MMM yyyy"));
            y += 20;
        }

        if (docs.Count > 0)
        {
            gfx.DrawLine(new XPen(XColor.FromArgb(229, 231, 235)), 32, y, page.Width - 32, y);
        }

        // Footer
        gfx.DrawString("Generated by DocVault  ·  Confidential",
            smallFont, new XSolidBrush(XColor.FromArgb(156, 163, 175)),
            new XRect(32, page.Height - 36, page.Width - 64, 20), XStringFormats.TopLeft);
    }

    public static void AddSeparatorPage(PdfDocument output, Document doc)
    {
        var page = output.AddPage();
        page.Width  = XUnit.FromPoint(595);
        page.Height = XUnit.FromPoint(842);

        using var gfx = XGraphics.FromPdfPage(page);

        // Accent bar
        gfx.DrawRectangle(new XSolidBrush(Purple), 0, 0, 6, page.Height);

        var h1     = new XFont("Arial", 18, XFontStyle.Bold);
        var label  = new XFont("Arial", 8,  XFontStyle.Bold);
        var value  = new XFont("Arial", 10, XFontStyle.Regular);
        var smallF = new XFont("Arial", 8,  XFontStyle.Regular);
        var gray   = new XSolidBrush(Gray);
        var black  = new XSolidBrush(XColor.FromArgb(17, 24, 39));

        gfx.DrawString(doc.Title, h1, black, new XRect(40, 80, page.Width - 80, 36), XStringFormats.TopLeft);

        var isPdf = Path.GetExtension(doc.OriginalFileName).Equals(".pdf", StringComparison.OrdinalIgnoreCase);
        gfx.DrawString(isPdf ? "Content follows on next page(s)" : "Content not embeddable (non-PDF file)",
            smallF, gray, new XRect(40, 118, page.Width - 80, 20), XStringFormats.TopLeft);

        // Divider
        gfx.DrawLine(new XPen(XColor.FromArgb(229, 231, 235)), 40, 148, page.Width - 40, 148);

        // Metadata grid
        var fields = new (string Label, string Value)[]
        {
            ("FILE NAME",      doc.OriginalFileName),
            ("DEPARTMENT",     doc.Department?.Name  ?? "—"),
            ("FINANCIAL YEAR", doc.FinancialYear?.Label ?? "—"),
            ("DOCUMENT TYPE",  doc.DocumentType?.Name ?? "—"),
            ("UPLOADER",       doc.User?.FullName ?? "—"),
            ("STATUS",         doc.Status),
            ("UPLOADED",       doc.UploadedAt.ToLocalTime().ToString("dd MMM yyyy HH:mm")),
            ("DESCRIPTION",    doc.Description ?? "—"),
        };

        double y = 168;
        bool left = true;
        double col1 = 40, col2 = page.Width / 2 + 10;

        foreach (var (lbl, val) in fields)
        {
            double x = left ? col1 : col2;
            gfx.DrawString(lbl, label, gray,  new XRect(x, y,      (page.Width / 2) - 20, 14), XStringFormats.TopLeft);
            gfx.DrawString(val, value, black, new XRect(x, y + 14, (page.Width / 2) - 20, 20), XStringFormats.TopLeft);

            if (!left) y += 48;
            left = !left;
        }
    }

    private static void DrawRow(XGraphics gfx, XFont font, XBrush brush, double y,
        string num, string title, string uploader, string dept, string fy, string date)
    {
        // Columns laid out left→right with no overlap (page width 595, margins 36/32)
        gfx.DrawString(num,      font, brush, new XRect(36,  y, 20,  16), XStringFormats.TopLeft);
        gfx.DrawString(title,    font, brush, new XRect(56,  y, 155, 16), XStringFormats.TopLeft);
        gfx.DrawString(uploader, font, brush, new XRect(211, y, 95,  16), XStringFormats.TopLeft);
        gfx.DrawString(dept,     font, brush, new XRect(306, y, 88,  16), XStringFormats.TopLeft);
        gfx.DrawString(fy,       font, brush, new XRect(394, y, 72,  16), XStringFormats.TopLeft);
        gfx.DrawString(date,     font, brush, new XRect(466, y, 97,  16), XStringFormats.TopLeft);
    }

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..(max - 1)] + "…";
}
